apiVersion: v1
kind: Service

metadata:
  name: diabetes-service
  
  labels:
    app: diabetes-app

spec:
  selector:
    app: diabetes-app

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000

  type: NodePort